"""Soft delete ve performans indeksleri eklendi

Revision ID: 2c50a9202d21
Revises: 
Create Date: 2026-03-16 22:04:13.190094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c50a9202d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakim_kaydi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bakim_kaydi_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bakim_kaydi_malzeme_id'), ['malzeme_id'], unique=False)

    with op.batch_alter_table('haber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_haber_tarih'), ['tarih'], unique=False)

    with op.batch_alter_table('havalimani', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_havalimani_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('islem_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_islem_log_kullanici_id'), ['kullanici_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_islem_log_zaman'), ['zaman'], unique=False)

    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kullanici_havalimani_id'), ['havalimani_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kullanici_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_kullanici_rol'), ['rol'], unique=False)

    with op.batch_alter_table('kutu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kutu_havalimani_id'), ['havalimani_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kutu_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('malzeme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_malzeme_durum'), ['durum'], unique=False)
        batch_op.create_index(batch_op.f('ix_malzeme_gelecek_bakim_tarihi'), ['gelecek_bakim_tarihi'], unique=False)
        batch_op.create_index(batch_op.f('ix_malzeme_havalimani_id'), ['havalimani_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_malzeme_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_malzeme_kutu_id'), ['kutu_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('malzeme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_malzeme_kutu_id'))
        batch_op.drop_index(batch_op.f('ix_malzeme_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_malzeme_havalimani_id'))
        batch_op.drop_index(batch_op.f('ix_malzeme_gelecek_bakim_tarihi'))
        batch_op.drop_index(batch_op.f('ix_malzeme_durum'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('kutu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kutu_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_kutu_havalimani_id'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanici_rol'))
        batch_op.drop_index(batch_op.f('ix_kullanici_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_kullanici_havalimani_id'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('islem_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_islem_log_zaman'))
        batch_op.drop_index(batch_op.f('ix_islem_log_kullanici_id'))

    with op.batch_alter_table('havalimani', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_havalimani_is_deleted'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('haber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_haber_tarih'))

    with op.batch_alter_table('bakim_kaydi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bakim_kaydi_malzeme_id'))
        batch_op.drop_index(batch_op.f('ix_bakim_kaydi_is_deleted'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
