"""schema sync after platform expansion

Revision ID: 6b2c217fb7ff
Revises: 2c50a9202d21
Create Date: 2026-03-18 20:14:48.322914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2c217fb7ff'
down_revision = '2c50a9202d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_lockout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=180), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_lockout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_lockout_identifier'), ['identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_lockout_locked_until'), ['locked_until'], unique=False)

    op.create_table('consumable_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('min_stock_level', sa.Float(), nullable=True),
    sa.Column('critical_level', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumable_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumable_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_item_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_consumable_item_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_item_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_item_title'), ['title'], unique=False)

    op.create_table('content_seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_content_seo_entity')
    )
    with op.batch_alter_table('content_seo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_seo_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_seo_entity_type'), ['entity_type'], unique=False)

    op.create_table('demo_seed_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_tag', sa.String(length=60), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('record_label', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_tag', 'model_name', 'record_id', name='uq_demo_seed_record')
    )
    with op.batch_alter_table('demo_seed_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demo_seed_record_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_demo_seed_record_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demo_seed_record_seed_tag'), ['seed_tag'], unique=False)

    op.create_table('document_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_resource_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_resource_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_resource_order_index'), ['order_index'], unique=False)

    op.create_table('home_quick_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=260), nullable=True),
    sa.Column('link_url', sa.String(length=350), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_quick_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_quick_link_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_home_quick_link_order_index'), ['order_index'], unique=False)

    op.create_table('home_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('subtitle', sa.String(length=250), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_section_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_home_section_order_index'), ['order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_home_section_section_key'), ['section_key'], unique=False)

    op.create_table('home_slider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('button_text', sa.String(length=80), nullable=True),
    sa.Column('button_link', sa.String(length=300), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_slider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_slider_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_home_slider_order_index'), ['order_index'], unique=False)

    op.create_table('home_stat_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('value_text', sa.String(length=80), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_stat_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_stat_card_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_home_stat_card_order_index'), ['order_index'], unique=False)

    op.create_table('maintenance_form_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('maintenance_form_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_form_template_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_form_template_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('nav_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_permission_module'), ['module'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_key'), ['key'], unique=True)

    op.create_table('site_ayarlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=True),
    sa.Column('alt_metin', sa.Text(), nullable=True),
    sa.Column('iletisim_notu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slider_resim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resim_url', sa.String(length=500), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=True),
    sa.Column('alt_yazi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_name'), ['name'], unique=True)

    op.create_table('equipment_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model_code', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_specs', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('maintenance_period_days', sa.Integer(), nullable=True),
    sa.Column('criticality_level', sa.String(length=20), nullable=True),
    sa.Column('default_maintenance_form_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_maintenance_form_id'], ['maintenance_form_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_template_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_template_criticality_level'), ['criticality_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_template_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_template_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_template_name'), ['name'], unique=False)

    op.create_table('maintenance_form_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_template_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['maintenance_form_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_form_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_form_field_form_template_id'), ['form_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_form_field_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permission_is_allowed'), ['is_allowed'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permission_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permission_role_id'), ['role_id'], unique=False)

    op.create_table('spare_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('compatible_asset_type', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model_code', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('min_stock_level', sa.Float(), nullable=True),
    sa.Column('critical_level', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_part_code'), ['part_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_spare_part_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_title'), ['title'], unique=False)

    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_slug'), ['slug'], unique=True)

    op.create_table('approval_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_type', sa.String(length=80), nullable=False),
    sa.Column('target_model', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_request_approval_type'), ['approval_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_target_model'), ['target_model'], unique=False)

    op.create_table('consumable_stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('kutu_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['havalimani.id'], ),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumable_item.id'], ),
    sa.ForeignKeyConstraint(['kutu_id'], ['kutu.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumable_stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumable_stock_movement_airport_id'), ['airport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_stock_movement_consumable_id'), ['consumable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_stock_movement_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_stock_movement_kutu_id'), ['kutu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_stock_movement_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_stock_movement_performed_by_id'), ['performed_by_id'], unique=False)

    op.create_table('content_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('last_edited_by_id', sa.Integer(), nullable=True),
    sa.Column('last_action', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_edited_by_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['published_by_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_content_workflow_entity')
    )
    with op.batch_alter_table('content_workflow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_workflow_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_workflow_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_workflow_last_edited_by_id'), ['last_edited_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_workflow_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_workflow_published_by_id'), ['published_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_workflow_status'), ['status'], unique=False)

    op.create_table('media_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=60), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_asset_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('spare_part_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False),
    sa.Column('quantity_reserved', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('shelf_location', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['havalimani.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spare_part_id', 'airport_id', name='uq_spare_part_airport_stock')
    )
    with op.batch_alter_table('spare_part_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_stock_airport_id'), ['airport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_stock_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_stock_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_stock_spare_part_id'), ['spare_part_id'], unique=False)

    op.create_table('user_permission_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=80), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_key', name='uq_user_permission_override')
    )
    with op.batch_alter_table('user_permission_override', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permission_override_is_allowed'), ['is_allowed'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_override_permission_key'), ['permission_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_override_user_id'), ['user_id'], unique=False)

    op.create_table('inventory_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_template_id', sa.Integer(), nullable=False),
    sa.Column('havalimani_id', sa.Integer(), nullable=False),
    sa.Column('legacy_material_id', sa.Integer(), nullable=True),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=120), nullable=True),
    sa.Column('qr_code', sa.String(length=150), nullable=True),
    sa.Column('asset_tag', sa.String(length=120), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('depot_location', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('maintenance_state', sa.String(length=30), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('last_calibration_date', sa.Date(), nullable=True),
    sa.Column('next_calibration_date', sa.Date(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('maintenance_period_days', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('last_meter_sync_at', sa.DateTime(), nullable=True),
    sa.Column('calibration_counter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_template_id'], ['equipment_template.id'], ),
    sa.ForeignKeyConstraint(['havalimani_id'], ['havalimani.id'], ),
    sa.ForeignKeyConstraint(['legacy_material_id'], ['malzeme.id'], ),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['inventory_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_asset_asset_tag'), ['asset_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_equipment_template_id'), ['equipment_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_havalimani_id'), ['havalimani_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_is_critical'), ['is_critical'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_last_meter_sync_at'), ['last_meter_sync_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_legacy_material_id'), ['legacy_material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_maintenance_state'), ['maintenance_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_next_maintenance_date'), ['next_maintenance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_parent_asset_id'), ['parent_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_qr_code'), ['qr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_asset_serial_no'), ['serial_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_asset_status'), ['status'], unique=False)

    op.create_table('asset_operational_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=30), nullable=False),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('service_provider', sa.String(length=150), nullable=True),
    sa.Column('service_note', sa.Text(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('lifecycle_note', sa.Text(), nullable=True),
    sa.Column('transfer_reference', sa.String(length=120), nullable=True),
    sa.Column('last_transfer_at', sa.DateTime(), nullable=True),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('out_of_service_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_operational_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_operational_state_asset_id'), ['asset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_operational_state_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_operational_state_lifecycle_status'), ['lifecycle_status'], unique=False)

    op.create_table('calibration_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('warning_days', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=True),
    sa.Column('certificate_template', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_schedule_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_schedule_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_schedule_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('maintenance_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('equipment_template_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('owner_airport_id', sa.Integer(), nullable=True),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.ForeignKeyConstraint(['equipment_template_id'], ['equipment_template.id'], ),
    sa.ForeignKeyConstraint(['owner_airport_id'], ['havalimani.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plan_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plan_equipment_template_id'), ['equipment_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plan_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plan_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plan_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plan_owner_airport_id'), ['owner_airport_id'], unique=False)

    op.create_table('meter_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('meter_type', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_template_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.ForeignKeyConstraint(['equipment_template_id'], ['equipment_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meter_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_definition_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_definition_equipment_template_id'), ['equipment_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_definition_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_definition_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_definition_meter_type'), ['meter_type'], unique=False)

    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_no', sa.String(length=30), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=30), nullable=False),
    sa.Column('work_order_type', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('sla_target_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('used_parts', sa.Text(), nullable=True),
    sa.Column('labor_hours', sa.Float(), nullable=True),
    sa.Column('labor_minutes', sa.Integer(), nullable=True),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('extra_notes', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('is_repeat_failure', sa.Boolean(), nullable=True),
    sa.Column('checklist_template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['maintenance_form_template.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['created_user_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_completed_by_id'), ['completed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_created_user_id'), ['created_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_is_repeat_failure'), ['is_repeat_failure'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_maintenance_type'), ['maintenance_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_sla_target_at'), ['sla_target_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_target_date'), ['target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_work_order_no'), ['work_order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_order_work_order_type'), ['work_order_type'], unique=False)

    op.create_table('asset_meter_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('meter_definition_id', sa.Integer(), nullable=False),
    sa.Column('reading_value', sa.Float(), nullable=False),
    sa.Column('reading_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.ForeignKeyConstraint(['meter_definition_id'], ['meter_definition.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_meter_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_meter_reading_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_meter_reading_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_meter_reading_meter_definition_id'), ['meter_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_meter_reading_reading_at'), ['reading_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_meter_reading_recorded_by_id'), ['recorded_by_id'], unique=False)

    op.create_table('calibration_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('calibration_schedule_id', sa.Integer(), nullable=True),
    sa.Column('calibration_date', sa.Date(), nullable=False),
    sa.Column('next_calibration_date', sa.Date(), nullable=True),
    sa.Column('calibrated_by_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=150), nullable=True),
    sa.Column('certificate_no', sa.String(length=120), nullable=True),
    sa.Column('certificate_file', sa.String(length=500), nullable=True),
    sa.Column('result_status', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.ForeignKeyConstraint(['calibrated_by_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['calibration_schedule_id'], ['calibration_schedule.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_record_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_calibrated_by_id'), ['calibrated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_calibration_date'), ['calibration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_calibration_schedule_id'), ['calibration_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_certificate_no'), ['certificate_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_next_calibration_date'), ['next_calibration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_result_status'), ['result_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_record_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('maintenance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=30), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('checklist_snapshot', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('inspection_score', sa.Float(), nullable=True),
    sa.Column('inspection_summary', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_history_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_history_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_history_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_history_performed_by_id'), ['performed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_history_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('maintenance_trigger_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('equipment_template_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('meter_definition_id', sa.Integer(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('warning_lead_value', sa.Float(), nullable=True),
    sa.Column('auto_create_work_order', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_trigger_reading', sa.Float(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['inventory_asset.id'], ),
    sa.ForeignKeyConstraint(['equipment_template_id'], ['equipment_template.id'], ),
    sa.ForeignKeyConstraint(['meter_definition_id'], ['meter_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_trigger_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_trigger_rule_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_trigger_rule_equipment_template_id'), ['equipment_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_trigger_rule_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_trigger_rule_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_trigger_rule_meter_definition_id'), ['meter_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_trigger_rule_trigger_type'), ['trigger_type'], unique=False)

    op.create_table('work_order_checklist_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=150), nullable=False),
    sa.Column('response_value', sa.Text(), nullable=True),
    sa.Column('responded_by_id', sa.Integer(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('is_failure', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['maintenance_form_field.id'], ),
    sa.ForeignKeyConstraint(['responded_by_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_checklist_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_checklist_response_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_checklist_response_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_checklist_response_is_failure'), ['is_failure'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_checklist_response_responded_by_id'), ['responded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_checklist_response_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_part_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('consumed_from_stock_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consumed_from_stock_id'], ['spare_part_stock.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_part_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_part_usage_consumed_from_stock_id'), ['consumed_from_stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_part_usage_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_part_usage_spare_part_id'), ['spare_part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_part_usage_work_order_id'), ['work_order_id'], unique=False)

    with op.batch_alter_table('islem_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('target_model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_islem_log_event_key'), ['event_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_islem_log_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_islem_log_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_islem_log_target_model'), ['target_model'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islem_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_islem_log_target_model'))
        batch_op.drop_index(batch_op.f('ix_islem_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_islem_log_outcome'))
        batch_op.drop_index(batch_op.f('ix_islem_log_event_key'))
        batch_op.drop_column('outcome')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_model')
        batch_op.drop_column('event_key')

    with op.batch_alter_table('work_order_part_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_part_usage_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_part_usage_spare_part_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_part_usage_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_work_order_part_usage_consumed_from_stock_id'))

    op.drop_table('work_order_part_usage')
    with op.batch_alter_table('work_order_checklist_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_checklist_response_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_checklist_response_responded_by_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_checklist_response_is_failure'))
        batch_op.drop_index(batch_op.f('ix_work_order_checklist_response_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_work_order_checklist_response_field_id'))

    op.drop_table('work_order_checklist_response')
    with op.batch_alter_table('maintenance_trigger_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_trigger_rule_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_maintenance_trigger_rule_meter_definition_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_trigger_rule_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_maintenance_trigger_rule_is_active'))
        batch_op.drop_index(batch_op.f('ix_maintenance_trigger_rule_equipment_template_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_trigger_rule_asset_id'))

    op.drop_table('maintenance_trigger_rule')
    with op.batch_alter_table('maintenance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_history_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_history_performed_by_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_history_performed_at'))
        batch_op.drop_index(batch_op.f('ix_maintenance_history_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_maintenance_history_asset_id'))

    op.drop_table('maintenance_history')
    with op.batch_alter_table('calibration_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_record_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_result_status'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_next_calibration_date'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_certificate_no'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_calibration_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_calibration_date'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_calibrated_by_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_record_asset_id'))

    op.drop_table('calibration_record')
    with op.batch_alter_table('asset_meter_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_meter_reading_recorded_by_id'))
        batch_op.drop_index(batch_op.f('ix_asset_meter_reading_reading_at'))
        batch_op.drop_index(batch_op.f('ix_asset_meter_reading_meter_definition_id'))
        batch_op.drop_index(batch_op.f('ix_asset_meter_reading_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_asset_meter_reading_asset_id'))

    op.drop_table('asset_meter_reading')
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_work_order_type'))
        batch_op.drop_index(batch_op.f('ix_work_order_work_order_no'))
        batch_op.drop_index(batch_op.f('ix_work_order_verification_status'))
        batch_op.drop_index(batch_op.f('ix_work_order_target_date'))
        batch_op.drop_index(batch_op.f('ix_work_order_status'))
        batch_op.drop_index(batch_op.f('ix_work_order_source_type'))
        batch_op.drop_index(batch_op.f('ix_work_order_sla_target_at'))
        batch_op.drop_index(batch_op.f('ix_work_order_priority'))
        batch_op.drop_index(batch_op.f('ix_work_order_maintenance_type'))
        batch_op.drop_index(batch_op.f('ix_work_order_is_repeat_failure'))
        batch_op.drop_index(batch_op.f('ix_work_order_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_work_order_created_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_completed_by_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_assigned_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_asset_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_approved_by_id'))

    op.drop_table('work_order')
    with op.batch_alter_table('meter_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_definition_meter_type'))
        batch_op.drop_index(batch_op.f('ix_meter_definition_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meter_definition_is_active'))
        batch_op.drop_index(batch_op.f('ix_meter_definition_equipment_template_id'))
        batch_op.drop_index(batch_op.f('ix_meter_definition_asset_id'))

    op.drop_table('meter_definition')
    with op.batch_alter_table('maintenance_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_owner_airport_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_next_due_date'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_is_active'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_equipment_template_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_asset_id'))

    op.drop_table('maintenance_plan')
    with op.batch_alter_table('calibration_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_schedule_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_calibration_schedule_is_active'))
        batch_op.drop_index(batch_op.f('ix_calibration_schedule_asset_id'))

    op.drop_table('calibration_schedule')
    with op.batch_alter_table('asset_operational_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_operational_state_lifecycle_status'))
        batch_op.drop_index(batch_op.f('ix_asset_operational_state_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_asset_operational_state_asset_id'))

    op.drop_table('asset_operational_state')
    with op.batch_alter_table('inventory_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_asset_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_serial_no'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_qr_code'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_parent_asset_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_next_maintenance_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_maintenance_state'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_legacy_material_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_last_meter_sync_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_is_critical'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_havalimani_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_equipment_template_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_asset_asset_tag'))

    op.drop_table('inventory_asset')
    with op.batch_alter_table('user_permission_override', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_override_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_override_permission_key'))
        batch_op.drop_index(batch_op.f('ix_user_permission_override_is_allowed'))

    op.drop_table('user_permission_override')
    with op.batch_alter_table('spare_part_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_stock_spare_part_id'))
        batch_op.drop_index(batch_op.f('ix_spare_part_stock_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_spare_part_stock_is_active'))
        batch_op.drop_index(batch_op.f('ix_spare_part_stock_airport_id'))

    op.drop_table('spare_part_stock')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_severity'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_asset_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_media_asset_is_active'))
        batch_op.drop_index(batch_op.f('ix_media_asset_file_type'))

    op.drop_table('media_asset')
    with op.batch_alter_table('content_workflow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_workflow_status'))
        batch_op.drop_index(batch_op.f('ix_content_workflow_published_by_id'))
        batch_op.drop_index(batch_op.f('ix_content_workflow_published_at'))
        batch_op.drop_index(batch_op.f('ix_content_workflow_last_edited_by_id'))
        batch_op.drop_index(batch_op.f('ix_content_workflow_entity_type'))
        batch_op.drop_index(batch_op.f('ix_content_workflow_entity_id'))

    op.drop_table('content_workflow')
    with op.batch_alter_table('consumable_stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumable_stock_movement_performed_by_id'))
        batch_op.drop_index(batch_op.f('ix_consumable_stock_movement_movement_type'))
        batch_op.drop_index(batch_op.f('ix_consumable_stock_movement_kutu_id'))
        batch_op.drop_index(batch_op.f('ix_consumable_stock_movement_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_consumable_stock_movement_consumable_id'))
        batch_op.drop_index(batch_op.f('ix_consumable_stock_movement_airport_id'))

    op.drop_table('consumable_stock_movement')
    with op.batch_alter_table('approval_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_request_target_model'))
        batch_op.drop_index(batch_op.f('ix_approval_request_target_id'))
        batch_op.drop_index(batch_op.f('ix_approval_request_status'))
        batch_op.drop_index(batch_op.f('ix_approval_request_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_approval_request_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_approval_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_approval_request_approved_by_id'))
        batch_op.drop_index(batch_op.f('ix_approval_request_approval_type'))

    op.drop_table('approval_request')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_slug'))
        batch_op.drop_index(batch_op.f('ix_announcement_published_at'))
        batch_op.drop_index(batch_op.f('ix_announcement_is_published'))
        batch_op.drop_index(batch_op.f('ix_announcement_author_id'))

    op.drop_table('announcement')
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_title'))
        batch_op.drop_index(batch_op.f('ix_spare_part_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_spare_part_part_code'))
        batch_op.drop_index(batch_op.f('ix_spare_part_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_spare_part_is_active'))
        batch_op.drop_index(batch_op.f('ix_spare_part_category'))

    op.drop_table('spare_part')
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permission_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permission_permission_id'))
        batch_op.drop_index(batch_op.f('ix_role_permission_is_allowed'))

    op.drop_table('role_permission')
    with op.batch_alter_table('maintenance_form_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_form_field_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_maintenance_form_field_form_template_id'))

    op.drop_table('maintenance_form_field')
    with op.batch_alter_table('equipment_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_template_name'))
        batch_op.drop_index(batch_op.f('ix_equipment_template_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_equipment_template_is_active'))
        batch_op.drop_index(batch_op.f('ix_equipment_template_criticality_level'))
        batch_op.drop_index(batch_op.f('ix_equipment_template_category'))

    op.drop_table('equipment_template')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_supplier_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_supplier_is_active'))

    op.drop_table('supplier')
    op.drop_table('slider_resim')
    op.drop_table('site_ayarlari')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_key'))
        batch_op.drop_index(batch_op.f('ix_role_is_system'))
        batch_op.drop_index(batch_op.f('ix_role_is_active'))

    op.drop_table('role')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_module'))
        batch_op.drop_index(batch_op.f('ix_permission_key'))
        batch_op.drop_index(batch_op.f('ix_permission_is_active'))

    op.drop_table('permission')
    op.drop_table('nav_menu')
    with op.batch_alter_table('maintenance_form_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_form_template_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_maintenance_form_template_is_active'))

    op.drop_table('maintenance_form_template')
    with op.batch_alter_table('home_stat_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_stat_card_order_index'))
        batch_op.drop_index(batch_op.f('ix_home_stat_card_is_active'))

    op.drop_table('home_stat_card')
    with op.batch_alter_table('home_slider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_slider_order_index'))
        batch_op.drop_index(batch_op.f('ix_home_slider_is_active'))

    op.drop_table('home_slider')
    with op.batch_alter_table('home_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_section_section_key'))
        batch_op.drop_index(batch_op.f('ix_home_section_order_index'))
        batch_op.drop_index(batch_op.f('ix_home_section_is_active'))

    op.drop_table('home_section')
    with op.batch_alter_table('home_quick_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_quick_link_order_index'))
        batch_op.drop_index(batch_op.f('ix_home_quick_link_is_active'))

    op.drop_table('home_quick_link')
    with op.batch_alter_table('document_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_resource_order_index'))
        batch_op.drop_index(batch_op.f('ix_document_resource_is_active'))
        batch_op.drop_index(batch_op.f('ix_document_resource_category'))

    op.drop_table('document_resource')
    with op.batch_alter_table('demo_seed_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demo_seed_record_seed_tag'))
        batch_op.drop_index(batch_op.f('ix_demo_seed_record_record_id'))
        batch_op.drop_index(batch_op.f('ix_demo_seed_record_model_name'))

    op.drop_table('demo_seed_record')
    with op.batch_alter_table('content_seo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_seo_entity_type'))
        batch_op.drop_index(batch_op.f('ix_content_seo_entity_id'))

    op.drop_table('content_seo')
    with op.batch_alter_table('consumable_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumable_item_title'))
        batch_op.drop_index(batch_op.f('ix_consumable_item_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_consumable_item_is_active'))
        batch_op.drop_index(batch_op.f('ix_consumable_item_code'))
        batch_op.drop_index(batch_op.f('ix_consumable_item_category'))

    op.drop_table('consumable_item')
    with op.batch_alter_table('auth_lockout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_lockout_locked_until'))
        batch_op.drop_index(batch_op.f('ix_auth_lockout_identifier'))

    op.drop_table('auth_lockout')
    # ### end Alembic commands ###
